### ISSUE TITLE
Clarify setup instructions?

### ISSUE THREAD

**Issue by binary132** [emacs-lsp/helm-lsp#1]
Hello,

I've added `(require 'helm-lsp)` to my C++ mode hook, and it looks nice when I invoke `M-x helm-lsp-workspace-symbol`, but I was under the impression this was for interactive usage with lsp.  I saw in your README.org that this is meant to be used to replace `lsp-mode`'s `xref-appropos` function, but I'm not clear on how to do this.  Can you please add a few words to clarify how to override that LSP functionality?

**Comment by yyoncho** [comment]
```
(define-key lsp-mode-map [remap xref-find-apropos] #'helm-lsp-workspace-symbol)
```

And now you can use `C-M-.` to trigger help-lsp.

**Comment by Ekleog** [comment]
@yyoncho Any way this could get in the README? I was about to ask the same question before seeing it already had a closed issue about it

**Comment by yyoncho** [comment]
Done: https://github.com/emacs-lsp/helm-lsp/commit/714685b3a729e2bb802d11dfb1279fed5e9657bf

**Comment by Ekleog** [comment]
Thank you!
