### ISSUE TITLE
helm-lsp in melpa-stable too old for melpa-stable lsp-mode version

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-lsp/helm-lsp#21]
If one runs both lsp-mode and helm-lsp 8.0.0 from melpa-stable, https://github.com/emacs-lsp/helm-lsp/issues/14 happens. Switching helm-lsp from melpa-stable to melpa fixes it - please consider making a new melpa-stable release?

**Comment by jcs090218** [comment]
Just released `0.3`, see https://github.com/emacs-lsp/helm-lsp/releases/tag/0.3.
