### ISSUE TITLE
helm-lsp-global-workspace-symbol fails to select a symbol over TRAMP

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-lsp/helm-lsp#5]
If an LSP project over TRAMP is opened, `helm-lsp-global-workspace-symbol` starts and produces the completion list, but selecting any item (including one in an already open buffer) results in the following: (note a spurious "|" at the end of file name)
```
Use M-x make-directory RET RET to create the directory and its parents
LSP ::foo.c| not in project or it is blacklisted.
```
And a new empty modified non-file-backed buffer created with a name "foo.c|"
An otherwise unrelated package in `auto-save-hook` helpfully points out an attempt to access remote file using local path:
```
Error in auto-save-hook (wakatime-save): (file-missing "Setting current directory" "No such file or directory" "/home/username/should/be/remote/path/")
```

**Comment by yyoncho** [comment]
This will solve your original report in reddit - how you can use **helm-lsp-workspace-symbol** to search in the current project in any folder part of the project. You could also use `helm-lsp-global-workspace-symbol` but only if all language servers are remote and running against the same server. Let me know if that is sufficient for you.

**Comment by yyoncho** [comment]
Also, you will need the latest `lsp-mode` since I pushed a fix in it too - https://github.com/emacs-lsp/lsp-mode/commit/d230f9cff9867a28d9b243cb06ff273e360f35e4

**Comment by laurynas-biveinis** [comment]
Thanks, that it is sufficient for me. Now I remap xref-find-apropos to helm-lsp-workspace-symbols in lsp-mode buffers and to helm-lsp-global-workspace-symbol in the global keymap. (I see I can use the non-global version there too). The limitation of all remote all same LSs does not bother me, I could imagine someone wanting to lift the latter part of it for remote multi-language projects though.
